pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = uri("https://maven.fabricmc.net/")
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id "fabric-loom" version "1.10.1"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        maven {
            name = "Fabric"
            url = uri("https://maven.fabricmc.net/")
        }

        maven {
            name = "Mojang"
            url = uri("https://libraries.minecraft.net/")
        }

        mavenCentral()
    }
}

rootProject.name = "Mindaz"
